#!/bin/sh

yt-dlp \
	"$@" \
	--ignore-errors \
	--download-archive yt-dlp-archive.txt \
	--output "[%(upload_date)s] %(title)s.%(ext)s" \
	--continue \
	--progress \
	--extract-audio \
	--audio-format flac \
	--audio-quality 0 \
	--sponsorblock-remove default
