#!/bin/sh

yt-dlp \
	"$@" \
	--ignore-errors \
	--download-archive archive.txt \
	--format "ba*" \
	--output "(%(upload_date)s) %(channel)s - %(title)s.%(ext)s" \
	--continue \
	--progress \
	--extract-audio \
	--audio-format mp3 \
	--audio-quality 0 \
	--sponsorblock-remove default
